@startsalt
{+
  <b>Portal del Alumno | Detalle de Solicitud de Dispensa
  ==
  {
    <b>ID Trámite: | DSP-2026-089
    <b>Estado Actual: | <b><color:orange>Solicitada</color>
  }
  --
  <b>Información de la Dispensa
  {
    Asignatura de la dispensa: | "Ingeniería de Software II"
    Tipo/Motivo de dispensa:   | "Solapamiento de horarios"
    Día(s) de la semana:       | "Miércoles"
    Franja horaria afectada:   | "10:00 - 12:00    "
    Asignatura solapada:       | "Arquitectura de Software"
    Justificación / Comentarios:| "                                                  "
    Documento adjunto:         | [ Descargar y Ver ] resguardo_matricula.pdf
  }
  --
  {
    [   Cerrar Detalles   ]
  }
}
@endsalt
