@startsalt
{+
  <b>Portal del Alumno | Nueva Solicitud de Dispensa
  ==
  <b>Información de la Dispensa
  --
  {
    Asignatura de la dispensa: | ^Seleccione Asignatura...^
    Tipo/Motivo de dispensa:   | ^Solapamiento de horarios^
    Día(s) de la semana:       | ^Miércoles^
    Franja horaria afectada:   | "10:00 - 12:00    "
    Asignatura solapada:       | ^Seleccione Asignatura...^
    Justificación / Comentarios:| "                                                  "
    Documento adjunto:         | [ Seleccionar Archivo... ] Ningún archivo seleccionado
  }
  --
  {
    [ <b>Enviar Solicitud</b> ] | [   Cancelar   ]
  }
}
@endsalt
