@startuml
title Ver Detalle Alumno
skinparam linetype polyline

state ALUMNOS_ABIERTO_INICIAL as "ALUMNOS_ABIERTO"
state ALUMNO_ABIERTO_COMP     as "ALUMNO_ABIERTO"

[*] -[#green]-> ALUMNOS_ABIERTO_INICIAL

ALUMNOS_ABIERTO_INICIAL -[#green]-> ALUMNO_ABIERTO_COMP : verDetalleAlumno()
note on link
<b>Profesor</b> se encuentra en ALUMNOS_ABIERTO
y solicita ver el detalle de un alumno específico.

<b>Sistema</b> recupera la información académica
y cambia el contexto a ALUMNO_ABIERTO.
end note

state ALUMNO_ABIERTO_COMP as "ALUMNO_ABIERTO" {

    state VisualizacionFicha
    state DecisionNavegacion

    [*] -[#green]-> VisualizacionFicha
    note on link
    <b>Sistema</b> muestra la ficha completa del alumno:
    • Datos personales y Foto
    • Resumen de asistencias y faltas
    end note

    VisualizacionFicha -[#green]-> DecisionNavegacion
    note on link
    <b>Profesor</b> revisa la información mostrada.

    <b>Profesor</b> solicita realizar una acción.
    end note

    DecisionNavegacion -[#green]-> [*]
}

ALUMNO_ABIERTO_COMP -[#red]-> ALUMNOS_ABIERTO_INICIAL : cerrarDetalleAlumno()
note on link
<b>Sistema</b> cierra la ficha del alumno
y muestra nuevamente el listado en ALUMNOS_ABIERTO.
end note

@enduml
