@startuml DiagramaDeCasosDeUsoAlumno
left to right direction
skinparam packageStyle rectangle

actor Alumno

    package "Dispensas" {
        usecase "crearSolicitudDispensa()"   as CrearSolicitudDispensa
        usecase "consultarEstadoDispensa()"        as ConsultarEstadoDispensa
        usecase "editarSolicitudDispensa()"  as EditarSolicitudDispensa
        usecase "cerrarSolicitudDispensa()"  as CerrarSolicitudDispensa
        usecase "guardarSolicitudDispensa()"  as GuardarSolicitudDispensa
    }



Alumno --> CrearSolicitudDispensa
Alumno --> ConsultarEstadoDispensa
Alumno --> EditarSolicitudDispensa
Alumno --> CerrarSolicitudDispensa
Alumno --> GuardarSolicitudDispensa
@enduml