@startuml abrirRecorridos

skinparam linetype polyline

state in1 as "UNIVERSIDAD_DISPONIBLE"
in1 -[#green]-> abrirRecorridos

state in2 as "RECORRIDO_ABIERTO"
in2 -[#green]-> abrirRecorridos

state abrirRecorridos as "abrirRecorridos()" {

    state " " as MostrandoLista
    state " " as FiltrandoLista

    [*] -[#green]-> MostrandoLista 
    note on link
    <b>Administrador</b> solicita abrir recorridos
    end note    
    
    MostrandoLista -[#green]-> FiltrandoLista
    note on link
    <b>Sistema</b> presenta lista de recorridos
    • ID y nombre de cada recorrido
    • Permite solicitar filtrar lista
    • Permite solicitar crear recorrido nuevo
    • Permite solicitar eliminar recorrido
    • Permite solicitar editar recorrido
    end note
    
    FiltrandoLista -[#green]-> FiltrandoLista
    note on link
    <b>Administrador</b> solicita filtrar lista
    <b>Sistema</b> presenta lista filtrada
    end note
    
    FiltrandoLista -[#green]-> [*]
    note on link
    <b>Administrador</b> solicita una de las opciones
    end note
}

abrirRecorridos -[#green]-> RECORRIDO_ABIERTO
note on link
editarRecorrido()
end note

abrirRecorridos -[#green]-> RECORRIDO_ABIERTO
note on link
crearRecorrido()
end note

abrirRecorridos -[#green]-> RECORRIDOS_ABIERTO
note on link
eliminarRecorrido()
end note

abrirRecorridos -[#green]-> UNIVERSIDAD_DISPONIBLE
note on link
completarGestion()
end note

@enduml
