@startsalt
{
  **Asignatura: Matemáticas I - Examen Parcial**
  --
  {#
    **Alumno** | **Acción**
    García López, Ana | [ Ver Examen ]
    Martínez Ruiz, Luis | [ Ver Examen ]
    Sánchez Pérez, Elena | [ Ver Examen ]
    Torres Vila, Jordi | [ Ver Examen ]
    López Castro, María | [ Ver Examen ]
  }
}
@endsalt