@startuml
title Abrir Lista

skinparam linetype polyline

state startState as "LISTAS_ABIERTO"
state endState1 as "LISTA_ABIERTA" 
state endState2 as "LISTAS_ABIERTO" 

startState -[#green]-> abrirLista
note on link
    <b>Usuario solicita</b>
    Abrir Lista
end note

state abrirLista as "abrirLista()" {
    state MostrarLista as " "

    ' 1. Inicio: El sistema muestra la lista
    [*] -[#green]-> MostrarLista
    note on link
        <b>Sistema muestra</b>
        la lista solicitada a por el usuario.
    end note

    ' 2. Fin: El caso de uso interno finaliza
    MostrarLista -[#green]-> [*]
}

abrirLista -[#green]-> endState1
note on link
    <b>editarListaAlumnos()</b>
end note

abrirLista -[#green]-> endState2
note on link
    <b>Guardar/Cerrar Lista()</b>
end note

@enduml