@startuml
title Cerrar Detalle Matrícula

skinparam linetype polyline

state startState as "MATRICULA_ABIERTA"
state endState as "MATRICULAS_ABIERTO"

startState -[#green]-> cerrarDetalleMatricula
note on link
    <b>Usuario solicita</b>
    Cerrar Detalle Matrícula
end note

state cerrarDetalleMatricula as "cerrarDetalleMatricula()" {
    state MuestraListado as " "

    ' 1. Inicio: El sistema realiza la acción
    [*] -[#green]-> MuestraListado
    note on link
        <b>Sistema presenta</b>
        la interfaz de listado general de matrículas.
    end note

    ' 2. Fin: El caso de uso interno finaliza
    MuestraListado -[#green]-> [*]
}

cerrarDetalleMatricula -[#green]-> endState

@enduml