@startuml
title Guardar Solicitud

skinparam linetype polyline

state startState as "SOLICITUD_DISPENSA_ABIERTA"
state endState as "DISPENSAS_ABIERTO"

startState -[#green]-> guardarSolicitud
note on link
    <b>Usuario solicita</b>
    Guardar Solicitud
end note

state guardarSolicitud as "guardarSolicitud()" {
    state ValidacionCompleta as " "
    state PersistirDatos as " "

    ' 1. Inicio: Validacion Final
    [*] -[#green]-> ValidacionCompleta
    note on link
        <b>Sistema completa la validación</b>
        de todos los campos.
    end note
    
    ' 2. Persistencia de Datos
    ValidacionCompleta -[#green]-> PersistirDatos
    note on link
        <b>Sistema completa la actualización</b>
        y guarda los datos en la base de datos.
    end note

    ' 3. Fin: El caso de uso interno finaliza
    PersistirDatos -[#green]-> [*]
}

guardarSolicitud -[#green]-> endState

@enduml