@startuml
title Cerrar Usuario
skinparam linetype polyline

state USUARIO_ABIERTO_INICIAL  as "USUARIO_ABIERTO"
state PROCESO_CIERRE_COMP      as "CERRANDO_VISTA"
state USUARIOS_ABIERTO_FINAL   as "USUARIOS_ABIERTO"

[*] -[#green]-> USUARIO_ABIERTO_INICIAL

USUARIO_ABIERTO_INICIAL -[#green]-> PROCESO_CIERRE_COMP : cerrarUsuario()
note on link 
<b>Administrador</b> solicita volver atrás.
end note

state PROCESO_CIERRE_COMP {

    state DescarteCambios

    DescarteCambios -[#green]-> [*]
    note on link
    <b>Sistema</b> libera la vista del detalle del usuario.
    end note

}

PROCESO_CIERRE_COMP -[#red]-> USUARIOS_ABIERTO_FINAL
note on link
<b>Sistema</b> muestra nuevamente el listado en USUARIOS_ABIERTO
sin aplicar cambios.
end note

@enduml
