@startuml
title Guardar Usuario
skinparam linetype polyline

state USUARIO_ABIERTO_INICIAL  as "USUARIO_ABIERTO"
state PROCESO_GUARDADO_COMP    as "PROCESANDO_GUARDADO"
state USUARIOS_ABIERTO_FINAL   as "USUARIOS_ABIERTO"

[*] -[#green]-> USUARIO_ABIERTO_INICIAL

USUARIO_ABIERTO_INICIAL -[#green]-> PROCESO_GUARDADO_COMP : guardarUsuario()
note on link
<b>Administrador</b> solicita guardar los cambios.
end note

state PROCESO_GUARDADO_COMP {

    state ValidacionDatos
    state PersistenciaDatos

    [*] -[#green]-> ValidacionDatos
    note on link
    <b>Sistema</b> verifica la integridad de la información
    (campos obligatorios, formato de email, etc.).
    end note

    ValidacionDatos -[#green]-> PersistenciaDatos
    note on link
    <b>Sistema</b> guarda los datos.
    end note

    PersistenciaDatos -[#green]-> [*]
}

PROCESO_GUARDADO_COMP -[#green]-> USUARIOS_ABIERTO_FINAL
note on link
<b>Sistema</b> confirma el éxito de la operación
y muestra nuevamente el listado en USUARIOS_ABIERTO
con la información actualizada.
end note

@enduml
