@startuml
left to right direction

'-------------------
' Universidad y Regiones
'-------------------
object "uneatlantico : Universidad" as uneatlantico {
    nombre = "Universidad Europea del Atlántico"
}

object "edificioPrincipal : Region" as edificioPrincipal {
    nombre = "Centro de estudios universitarios"
}

object "exterior : Region" as exterior {
    nombre = "Zona exterior"
}

'-------------------
' Plantas
'-------------------
object "sotano3 : Planta" as sotano3 {
    nombre = "Sótano 3"
}

object "planta0 : Planta" as planta0 {
    nombre = "Planta Baja"
}

object "planta_2 : Planta" as planta_2 {
    nombre = "Planta -2"
}

object "plantaExterior : Planta" as plantaExterior {
    nombre = "Planta exterior"
}

'-------------------
' Pasillos
'-------------------
object "Pasillo -2 : Espacio" as pasillo_2 {
    nombre = "Pasillo -2"
    tipo = "Entrada"
}

object "Pasillo 0 : Espacio" as pasillo0 {
    nombre = "Pasillo 0"
    tipo = "Entrada"
}

'-------------------
' Espacios
'-------------------
object "aula1 : Espacio" as aula1 {
    nombre = "Aula 0.1"
    tipo = "Aula"
}

object "entrada : Espacio" as entrada {
    nombre = "Entrada a la universidad"
    tipo = "Entrada"
}

object "ORI : Espacio" as ORI {
    nombre = "ORI"
    tipo = "Oficina"
}

object "cafeteria : Espacio" as cafeteria {
    nombre = "Cafetería"
    tipo = "Cafeteria"
}

object "aula6 : Espacio" as aula6 {
    nombre = "Aula -2.6"
    tipo = "Laboratorio"
}

object "parkingSotano : Espacio" as parkingSotano {
    nombre = "Estacionamiento Sotano"
    tipo = "Parking"
}

object "areaVerde1 : Espacio" as areaVerde1 {
    nombre = "Área Verde 1"
    tipo = "AreaVerde"
}

object "canchaPadel1 : Espacio" as canchaPadel1 {
    nombre = "Cancha de Padel"
    tipo = "AreaDeportiva"
}

object "pabellon : Espacio" as pabellon {
    nombre = "Pabellón Deportivo"
    tipo = "AreaDeportiva"
}

'-------------------
' Visitante y Recorrido
'-------------------
object "Pablo : Visitante" as visitante {
    nombre = "Pablo"
}

map "TourEspacios : Recorrido" as recorrido {
 1 => Entrada
 2 => Pasillo 0
 3 => Aula 0.1
 4 => Pasillo 0
 5 => Pasillo -2
 6 => Cafetería
 7 => Pasillo -2
 8 => Pasillo 0
 9 => Entrada
 10 => Pabellón
}

'-------------------
' Relaciones de jerarquía
'-------------------
uneatlantico *-- edificioPrincipal
uneatlantico *-- exterior

edificioPrincipal *-- sotano3
edificioPrincipal *-- planta0
edificioPrincipal *-- planta_2

planta0 *-- aula1
planta0 *-- ORI
planta0 *-- entrada
planta0 *-- pasillo0
sotano3 o-- parkingSotano

planta_2 *-- cafeteria
planta_2 *-- aula6
planta_2 *-- pasillo_2

exterior *-- plantaExterior

plantaExterior *-- areaVerde1
plantaExterior *-- canchaPadel1
plantaExterior *-- pabellon

'-------------------
' Relaciones del recorrido
'-------------------
visitante --> recorrido
recorrido::1 o-- entrada
recorrido::2 o-- pasillo0
recorrido::3 o-- aula1
recorrido::5 o-- pasillo_2
recorrido::6 o-- cafeteria
recorrido::10 o-- pabellon


@enduml
