@startuml actoresYCasosDeUso-docente-maestro

left to right direction

actor "Docente" as doc

package "Módulo Grado" {
  usecase "crearGrado()" as UC1
  usecase "verGrados()" as UC2
  usecase "editarGrado()" as UC3
  usecase "eliminarGrado()" as UC4
}

package "Módulo Asignatura" {
  usecase "crearAsignatura()" as UC5
  usecase "verAsignaturas()" as UC6
  usecase "editarAsignatura()" as UC7
  usecase "eliminarAsignatura()" as UC8
}

package "Módulo Alumno" {
  usecase "crearAlumno()" as UC9
  usecase "verAlumnos()" as UC10
  usecase "editarAlumno()" as UC11
  usecase "eliminarAlumno()" as UC12
}

package "Módulo Preguntas-Respuestas" {
  usecase "crearPregunta()" as UC20
  usecase "verPreguntas()" as UC21
  usecase "editarPregunta" as UC22
  usecase "eliminarPregunta()" as UC23
 
  usecase "crearRespuesta()" as UC32
  usecase "verRespuestas()" as UC33
  usecase "editarRespuesta()" as UC34
  usecase "eliminarRespuesta()" as UC35
}




doc -r-> UC1
doc -r-> UC2
doc -r-> UC3
doc -r-> UC4

doc -u-> UC5
doc -u-> UC6
doc -u-> UC7
doc -u-> UC8

doc -u-> UC9
doc -u-> UC10
doc -u-> UC11
doc -u-> UC12

doc --> UC20
doc --> UC21
doc --> UC22
doc --> UC23

doc --> UC32
doc --> UC33
doc --> UC34
doc --> UC35


@enduml