@startuml EstadoListaAlumno
title Estado de Lista de Alumnos

skinparam linetype polyline

[*] --> Disponible : importarListaDeAlumnos()

Disponible --> En_actualizacion : detectarCambiosExternos()
En_actualizacion --> Disponible : aplicarActualizacionLista()

Disponible --> Cerrada : cerrarPeriodoAcademico()
Cerrada --> [*]
@enduml