@startuml
skinparam linetype polyline

state in1 as "RECORRIDO_ABIERTOS"
in1 -[#green]-> verEspaciosCercanos
state in2 as "ESPACIO_ABIERTO"
in2 -[#green]-> verEspaciosCercanos

state verEspaciosCercanos as "verEspaciosCercanos()" {
    state " " as SolicitandoEspaciosCercanos
    state ConsultandoEspaciosCercanos
    state c <<choice>>

    [*] -[#green]-> SolicitandoEspaciosCercanos 
    note on link
    <b>Visitante</b> solicita ver espacios cercanos
    end note    
    
    SolicitandoEspaciosCercanos -[#green]-> ConsultandoEspaciosCercanos
    note on link
    <b>Sistema</b> presenta
    • lista de espacios cercanos
    end note
    
    ConsultandoEspaciosCercanos -[#green]-> c
    note on link
    <b>Visitante</b> solicita
    • continuar consultando
    • salir de espacios cercanos
    end note
    
    c -[#green]-> ConsultandoEspaciosCercanos
    note on link
    continuar consultando
    end note

    c -[#green]-> [*]
    note on link
    salir de espacios cercanos
    end note
}

verEspaciosCercanos -[#green]-> ESPACIO_ABIERTO
note on link
regresa
end note
@enduml
