@startuml
skinparam linetype polyline

state in1 as "ESPACIO_ABIERTO"
in1 -[#green]-> cambiarDeEspacio
state in2 as "RECORRIDO_ABIERTO"
in2 -[#green]-> cambiarDeEspacio

state cambiarDeEspacio as "cambiarDeEspacio()" {
    state " " as SolicitandoCambio
    state SeleccionandoUbicacion
    state c <<choice>>

    [*] -[#green]-> SolicitandoCambio 
    note on link
    <b>Visitante</b> solicita cambiar 
                     su ubicación actual
    end note    
    
    SolicitandoCambio -[#green]-> SeleccionandoEsapcio
    note on link
    <b>Sistema</b> presenta
    • Opciones de ubicación
    • Mapa interactivo
    end note
    
    SeleccionandoUbicacion -[#green]-> c 
    note on link
    <b>Visitante</b> solicita
    • confirmar nueva ubicación
    • cancelar cambio
    end note
    
        c -[#green]-> [*]
    note on link
    confirmar / cancelar
    end note
}

' ← CONTEXTUALIZADO correctamente:
ESPACIO_ABIERTO --> cambiarDeEspacio : cambiarDeEspacio()
cambiarDeEspacio --> ESPACIO_ABIERTO : ubicacionConfirmada()
@enduml
