@startuml
skinparam linetype polyline

state in1 as "UNIVERSIDAD_DISPONIBLE"
in1 -[#green]-> abrirEspacios

state buscarEspacio as "buscarEspacio()" {

    state " " as SolicitandoBusqueda
    state "MostrandoResultados" as MostrandoResultados
    state c <<choice>>

    [*] -[#green]-> SolicitandoBusqueda 
    note on link
    <b>Visitante</b> solicita buscar 
                     una ubicación
    end note    
    
    SolicitandoBusqueda -[#green]-> MostrandoResultados
    note on link
    <b>Sistema</b> presenta
    • Resultados de búsqueda
    end note
    
     MostrandoResultados -[#green]-> c
    note on link
    <b>Visitante</b> solicita
    • seleccionar ubicación
    • realizar nueva búsqueda
    • salir de búsqueda
    end note
    
    c -[#green]-> SolicitandoBusqueda
    note on link
    realizar nueva búsqueda
    end note

    c -[#green]-> [*]
    note on link
    seleccionar ubicación /
    salir de búsqueda
    end note
}

buscarEspacio -[#green]->RECORRIDO_ABIERTO
note on link
regresa
end note
@enduml
