@startsalt
{+
  <b>Portal de la Secretaría | Ingresar Solicitud de Dispensa
  ==
  <b>Registro de Dispensa (Modo Secretaría)
  --
  <b>Información del Alumno y Dispensa
  {
    Alumno Solicitante: | ^Buscar por DNI o Nombre...^
    Asignatura de la dispensa: | ^Seleccione Asignatura...^
    Tipo/Motivo de dispensa:   | ^Solapamiento de horarios^
    Día(s) de la semana:       | ^Miércoles^
    Franja horaria afectada:   | "10:00 - 12:00    "
    Asignatura solapada:       | ^Seleccione Asignatura...^
    Justificación / Comentarios:| "                                                  "
    Documento adjunto:         | [ Seleccionar Archivo... ] Ningún archivo seleccionado
  }
  --
  {
    [ <b>Registrar Solicitud en el Sistema</b> ] | [   Cancelar   ]
  }
}
@endsalt
